name: Bug Report
description: This is the form for reporting any bug you found on the program.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - Alv777
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce the error?
      description: Explain the exact steps you did to get the bug.
      placeholder: First, I ran the program and then pressed...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which operating system are you running?
      multiple: true
      options:
        - MacOS
        - Windows
        - Linux
  - type: textarea
    id: screenshots
    attributes:
      label: [OPTIONAL] Screenshots
      description: You can attach here screenshots you think could help explain the problem better.
      placeholder: Drop an image here or click below on "Attach files".
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        Thank you so much for taking your time to report the bug!
